service: graphql-inversify-api-gateway

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region}
  accountId: ${opt:accountId}

plugins:
  - serverless-offline


provider:
  name: aws
  runtime: nodejs10.x
  environment:
    SECRETS_MANAGER_KEY: ${opt:secretManagerKey}
    DATABASE_NAME: ${opt:databaseName}
    REGION: "us-east-1"
    NODE_ENV: "production"
  iamRoleStatements: ${file(sls/role/iamRoleStatement.yml)}
  stackTags:
    "Name": "Graphql-Inversify-API-Gateway-Demo"
  tracing:
    apiGateway: true
    lambda: true

functions:
  movieService: ${file(sls/lambda/movieService.yml)}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
      GatewayResponseDefault5XX:
        Type: 'AWS::ApiGateway::GatewayResponse'
        Properties:
          ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          ResponseType: DEFAULT_5XX
          RestApiId:
            Ref: 'ApiGatewayRestApi'

package:
  exclude:
    - ./**
  include:
    - src/**
    - '*.js'
    - node_modules/**

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
