export const TYPE = {
  Logger: Symbol('logger'),
  Config: Symbol('Config'),
  RdsConfig: Symbol('RdsConfig'),
  RdsProvider: Symbol('RdsProvider'),
  SecretsManagerProvider: Symbol('SecretsManagerProvider'),
  SecretsService: Symbol('SecretsService'),
  BaseService: Symbol('BaseService'),
  MovieService: Symbol('MovieService'),
  RdsGraphQlServerFactory: Symbol('RdsGraphQlServerFactory'),
  Connection: Symbol('Connection'),
  SecretsManagerClient: Symbol('SecretsManagerClient'),
  AppConfigProvider: Symbol('AppConfigProvider'),
  AppConfigService: Symbol('AppConfigService'),
  AppConfigParameters: Symbol('AppConfigParameters'),
};
