version: '3'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=movie_db -user=root -password=banana -connectRetries=120 migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=banana
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
